version: 2
jobs:
  build:
    working_directory: ~/pgql-api

    docker:
      - image: circleci/node:12.13.0
        environment:
          APP_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/pgql_api_test
          NODE_ENV: test
          PORT: "8080"
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pgql_api_test
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm run test:cov -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results/mocha/results.xml

      - store_test_results:
          path: ~/pgql-api/test-results

      - run:
          name: Report Coverage
          command: cat ./coverage/lcov.info | npx codacy-coverage
