#!/bin/bash

cd "$(dirname "$0")/.." || return

export DBENV=test
export NODE_ENV=test
export COMPOSE_PROJECT_NAME=pgql-api-test

script/update

LEAVE_UP=true script/migrate

docker-compose run --rm server npm run test:cov
